### ISSUE TITLE
Not generating Util methods neither the list

### ISSUE THREAD

**Issue by lucasmontec** [ByronMayne/ScriptForge#6]
Lastest version is not generating neither the util scene validation methods, nor the read-only list.
Also, it would be nice if you don't allocate anything on that class. Since is a generated class, there is no need to use new for the read-only access.

**Comment by ByronMayne** [comment]
The helper functions have been added back in the last commit. They were lost when I removed the original templates. 

For the list there is no way to protect an array from modifications. There is no `public readonly string[]`, that is really a compile warning in C#. You can stop the array from being set to a new reference but the elements can still be modified. Unity takes the approach of returning a new array each time. I have change it from that to a `ReadOnlyCollection<string>`. This is one way to try to protect users from modifying something when they should not be able to.
